project:
  type: website
  resources: 
    - "*.gif"
    - "*.mp4"

execute:
  freeze: auto

website:
  title: "Broadway Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: overall_broadway_trends.qmd
        text: Overall
      - href: top_broadway_trends.qmd
        text: Top Shows
      - about.qmd
      - href: sources.qmd
        text: Sources
      

format:
  html:
    theme: flatly
    toc: true
