project:
  type: website
  resources: 
    - "*.gif"
    - "*.mp4"

execute:
  freeze: auto

website:
  title: "broadway_project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    toc: true
